//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMyBandTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConciertosCR
    {
        public int id { get; set; }
        public string Codigo { get; set; }
        public string Banda { get; set; }
        public string Genero { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Pais { get; set; }
        public string Lugar { get; set; }
    }
}
