//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMyBandTour.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_MyBandTourEntities : DbContext
    {
        public BD_MyBandTourEntities()
            : base("name=BD_MyBandTourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConciertosCR> ConciertosCRs { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual int pr_Autenticar(string usuario, string password, ObjectParameter resultado)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Autenticar", usuarioParameter, passwordParameter, resultado);
        }
    
        public virtual ObjectResult<pr_ConsultarConciertos_Result> pr_ConsultarConciertos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_ConsultarConciertos_Result>("pr_ConsultarConciertos");
        }
    
        public virtual int pr_EliminarConcierto(string codigo, ObjectParameter resultado)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_EliminarConcierto", codigoParameter, resultado);
        }
    
        public virtual int pr_InsertarConciertoCR(string codigo, string banda, string genero, Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> hora, string pais, string lugar, ObjectParameter resultado)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var bandaParameter = banda != null ?
                new ObjectParameter("Banda", banda) :
                new ObjectParameter("Banda", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("Hora", hora) :
                new ObjectParameter("Hora", typeof(System.TimeSpan));
    
            var paisParameter = pais != null ?
                new ObjectParameter("Pais", pais) :
                new ObjectParameter("Pais", typeof(string));
    
            var lugarParameter = lugar != null ?
                new ObjectParameter("Lugar", lugar) :
                new ObjectParameter("Lugar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_InsertarConciertoCR", codigoParameter, bandaParameter, generoParameter, fechaParameter, horaParameter, paisParameter, lugarParameter, resultado);
        }
    
        public virtual int pr_InsertarUsuario(string usuario, string password, ObjectParameter resultado)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_InsertarUsuario", usuarioParameter, passwordParameter, resultado);
        }
    
        public virtual int pr_ModificarConcierto(string codigo, string banda, string genero, Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> hora, string pais, string lugar, ObjectParameter resultado)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var bandaParameter = banda != null ?
                new ObjectParameter("Banda", banda) :
                new ObjectParameter("Banda", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("Hora", hora) :
                new ObjectParameter("Hora", typeof(System.TimeSpan));
    
            var paisParameter = pais != null ?
                new ObjectParameter("Pais", pais) :
                new ObjectParameter("Pais", typeof(string));
    
            var lugarParameter = lugar != null ?
                new ObjectParameter("Lugar", lugar) :
                new ObjectParameter("Lugar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_ModificarConcierto", codigoParameter, bandaParameter, generoParameter, fechaParameter, horaParameter, paisParameter, lugarParameter, resultado);
        }
    }
}
